# Generated by Django 2.0.5 on 2018-08-23 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_blog_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
    ]
